### ISSUE TITLE
Importing safexwallet.dat and clicking import does nothing.

### ISSUE THREAD

**Issue by okbrown** [safex/safex_wallet#19]
Hi, 

just downloaded version 0.0.3 and i am able select the file `safexwallet.dat` but after entering my password and pressing `import` nothing happens.

is there something else i need to know?

**Comment by mdzor** [comment]
Have you done a wallet reset before ? 
When doing so - you can back-up your wallet and be able to import it.

Right now it's showing "safexwallet.dat" even if the file doesn't exist, fix is ready - it will display empty filename when the file is not present, to avoid confusion. 

https://github.com/safex/safex_wallet/pull/13

**Comment by okbrown** [comment]
Thanks I will give it another try.

**Comment by getbitcash** [comment]
I can not login into my wallet to save the dat file

**Comment by mdzor** [comment]
@getbitcash please open another issue if its still a problem

**Comment by okbrown** [comment]
No joy, issue still remains

**Comment by mdzor** [comment]
@okbrown which version of the wallet do you have ? 
latest is 0.0.5

**Comment by okbrown** [comment]
@mdzor I have `https://github.com/safex/safex_wallet/releases/tag/0.0.5` installed.

**Comment by mdzor** [comment]
Have you managed to open it with previous versions ? If you get 0.0.2 can you open it ?
Im trying to understand if changes in wallet backup format has been done in between versions.

**Comment by okbrown** [comment]
Sorry, i know its been a while but the issue still persists, tried importing on all versions. 😞

**Comment by Kiu0612** [comment]
Import wallet feature has been significantly improved in the new version. 
Now it allows importing the .dat wallet backup files. 
If you don't have a wallet and import the .dat file, it will create a new wallet with the keys from the backup.
If you already have a wallet, and want to import different keys in it, you can import the .dat file, wallet will then compare the different keys you already have with the ones you do not. It will then add only keys which are different from the ones you already have in wallet.

**Comment by okbrown** [comment]
Sorry this process still does not work.

Can you provide some clear and simple documentation on how to restore my .dat file please.
I also have the `xxxxsafexwallet` and `xxxunsafex` files as well

Thanks.

**Comment by okbrown** [comment]
So for anyone who like me was not able to import their `dat` file, after rebuilding their computer for example. 

1. Simply create a new wallet
2. Then in the field left of the`Import Key` button enter your private key.
3. Then press `Import Key`
4. Volia!
