### ISSUE TITLE
The password field does not support pasting from clipboard.

### ISSUE THREAD

**Issue by futursolo** [safex/safex_wallet#2]
I am using a password manager to manage all my passwords including the one for my SafeX wallet (which is literally a machine-generated meaningless string).

However, the current safex wallet does not support to paste the password from the clip board. Thus, I have to type my password into the app every time I open the wallet which really impacts my user experience.

Please support pasting passwords from the clipboard.

System: macOS Sierra 10.12.6
Wallet: SafeXWallet 0.0.1

**Comment by ddabek** [comment]
You can copy and paste with right-click,

but not yet with keyboard short cuts.. we'll still need to get back to this one...

**Comment by goh1** [comment]
Hi It appears that the wallet Private key cannot be encrypted?

**Comment by ddabek** [comment]
can you elaborate?

**Comment by goh1** [comment]
yes. At the SafeX wallet "settings"  "export unencrypted private" is the heading. It looks like the private key that i want to export is not encrypted. To know so that i can take the necessary precaution. Thanks

**Comment by ddabek** [comment]
Yes there is an option to export the keys unencrypted. If you want to export them encrypted then use the other option "export encrypted wallet (.dat)" this file you can only open using your password

**Comment by goh1** [comment]
Thank you. After exporting the encrypted password what apps should i used
to open for eg. notepad, internet explorer or..

**Comment by goh1** [comment]
Oh by the way do you know Bittrex exchange, does it support Bitcoingold
after the bitcoin fork.  That is  i do not need to do anything.

**Comment by goh1** [comment]
Hi Daniel . Sorry to bother you. I have downloaded the safex Wallet and
have transfer a little BTC to the wallet. It was ok on my 1st transfer.
Today A msg "Installation failed check with the owner with change log. Do
you think i should uninstall and reinstalled again.

Thank you
