### ISSUE TITLE
Balances don't show when in archive

### ISSUE THREAD

**Issue by ddabek** [safex/safex_wallet#26]
When you have an address in the archive, the balance is not checked.

**Comment by Kiu0612** [comment]
This bug has been fixed in the previous merge.

<img width="961" alt="40119596-67e7521c-591d-11e8-9d28-8fba95adda7f" src="https://user-images.githubusercontent.com/20647765/40589895-f3a078d4-61f5-11e8-8f09-c201be1c2f38.png">

@ddabek Please review changes and close the issue.
