### ISSUE TITLE
A complete log of this run can be found in: npm ERR!     ~/.npm/_logs/2018-11-10T04_30_10_800Z-debug.log

### ISSUE THREAD

**Issue by deba10106** [safex/safex_wallet#46]
I get the following error on ubuntu 18.04 while running sudo npm run make-all-installers

> SafexWallet@0.0.7 make-all-installers /home/omaxxx/Downloads/safex_wallet-0.0.7
> npm run build && electron-builder build -ml && electron-builder build -w --x64 --ia32

> SafexWallet@0.0.7 build /home/omaxxx/Downloads/safex_wallet-0.0.7
> react-scripts build

sh: 1: react-scripts: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! SafexWallet@0.0.7 build: `react-scripts build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the SafexWallet@0.0.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/omaxxx/.npm/_logs/2018-11-10T04_30_10_787Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SafexWallet@0.0.7 make-all-installers: `npm run build && electron-builder build -ml && electron-builder build -w --x64 --ia32`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the SafexWallet@0.0.7 make-all-installers script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/omaxxx/.npm/_logs/2018-11-10T04_30_10_800Z-debug.log

**Comment by ddabek** [comment]
`sudo npm run make-all-installers`

This is a command for development use only; im not sure it is necessary to work for you, thank you for reporting though.

**Comment by deba10106** [comment]
I ran npm start  and sudo npm start but got similar error! It says node_modules missing!!

npm ERR! path /home/omaxxx/.npm/_logs/2018-11-10T04_19_37_186Z-debug.log
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/home/omaxxx/.npm/_logs/2018-11-10T04_19_37_186Z-debug.log'
npm ERR!     at Object.fs.unlinkSync (fs.js:1061:18)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:336:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at Glob.emit (events.js:211:7)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!  { Error: EACCES: permission denied, unlink '/home/omaxxx/.npm/_logs/2018-11-10T04_19_37_186Z-debug.log'
npm ERR!     at Object.fs.unlinkSync (fs.js:1061:18)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:336:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at Glob.emit (events.js:211:7)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!   stack: 'Error: EACCES: permission denied, unlink \'/home/omaxxx/.npm/_logs/2018-11-10T04_19_37_186Z-debug.log\'\n    at Object.fs.unlinkSync (fs.js:1061:18)\n    at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:336:20\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)\n    at emitOne (events.js:116:13)\n    at Glob.emit (events.js:211:7)\n    at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)\n    at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)\n    at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/home/omaxxx/.npm/_logs/2018-11-10T04_19_37_186Z-debug.log' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

> SafexWallet@0.0.7 start /home/omaxxx/Downloads/safex_wallet-0.0.7
> react-scripts start

sh: 1: react-scripts: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! SafexWallet@0.0.7 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the SafexWallet@0.0.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by ddabek** [comment]
you need to run `npm install` first

then `npm run dev`

**Comment by JeffersonJeffy** [comment]
![ionic pb](https://user-images.githubusercontent.com/38722923/57638031-c7484780-75a4-11e9-86e6-017543f86e51.PNG)

**Comment by JeffersonJeffy** [comment]
je ne comprend pas pourquoi après la creation d'un projet j'ai cet erreur.
que faire

**Comment by Bansi23** [comment]
commands:
1.install yarn
2.npm start
