### ISSUE TITLE
Generates only "old" addresses, can not import keys of new wallets e.g. from miner

### ISSUE THREAD

**Issue by TheShaman** [safex/safex_wallet#48]
Maybe I am missing something here... 

The wallet by default generates old, bitcoin-style, addresses. 
Without funds, it refuses to "migrate" those addresses to the new Safex... addresses. 

New Safex... addresses generated e.g. with the one-click miner: can not be imported.
"invalid private key".

So how is a new user supposed to get a working address of the new format into this wallet?

Thanks for enlightenment.

**Comment by atanmarko** [comment]
We are preparing new _safex_wallet_ release that will have full support for Safex native blockchain (previous release has only migration support). Currently there is full featured command line wallet and json-rpc wallet from _safexcore_ project, nodejs wallet library _safex-nodejs-libwallet_, and some basic wallet support in _safex_miner_ (source code from master branch). At this moment not very user friendly, I know, but that is soon to be changed.

**Comment by TheShaman** [comment]
okok, got it :rofl: 

Not a problem at all, was just wondering if I was too dumb or if the functionality is just not yet there... 

Will wait patiently (well, more or less patiently, lol)
